# Generated by Django 3.2.10 on 2022-02-25 10:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tk',
            field=models.CharField(default=uuid.UUID('9bbb4530-7162-49cb-8382-6f34982e0eca'), max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
