# Generated by Django 3.2.10 on 2022-02-25 17:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_tk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tk',
            field=models.CharField(default=uuid.UUID('49c299d4-558c-4f98-a5ea-c8b620a2e1b7'), max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
