# Generated by Django 3.2.10 on 2022-02-25 20:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_tk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tk',
            field=models.CharField(default=uuid.UUID('171ebc2f-6592-43b8-afe1-9c7e7df15da7'), max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
