# Generated by Django 3.2.10 on 2022-02-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='lg',
            field=models.CharField(max_length=30, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='language',
            name='percent',
            field=models.CharField(choices=[('green', 'GREEN'), ('blue', 'BLUE'), ('red', 'RED'), ('orange', 'ORANGE'), ('black', 'BLACK')], default='green', max_length=30, verbose_name='How good are you at this language? 1 to 100'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='sk',
            field=models.CharField(max_length=30, verbose_name='Skill'),
        ),
    ]
