# Generated by Django 3.2.10 on 2022-02-25 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('front', '0002_auto_20220225_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='language',
            name='lg',
            field=models.CharField(max_length=50, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='language',
            name='percent',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='intermediate', max_length=30, verbose_name='How good are you?'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='percent',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='intermediate', max_length=30, verbose_name='How good are you?'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='sk',
            field=models.CharField(max_length=50, verbose_name='Skill'),
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
