# Generated by Django 3.2.10 on 2022-02-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_auto_20220225_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='education',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='objective',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
