# Generated by Django 3.2.10 on 2022-02-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0004_auto_20220225_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='work_description',
            field=models.TextField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='education',
            name='description',
            field=models.TextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='objective',
            name='description',
            field=models.TextField(max_length=1500),
        ),
    ]
