# Generated by Django 3.2.10 on 2022-02-25 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0005_auto_20220225_1937'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ['-start_date']},
        ),
    ]
